### ISSUE TITLE
tensorflow.python.framework.errors_impl.NotFoundError: /home/robot/learning_to_sample/classification/structural_losses/tf_nndistance_so.so: undefined symbol: _ZTIN10tensorflow8OpKernelE

### ISSUE THREAD

**Issue by TheJasal** [orendv/learning_to_sample#3]
After I trained Pointnet ang got the classification model, I run "python train_SNET.py --classifier_model_path log/baseline/PointNet1024/model.ckpt --num_out_points 64 --log_dir log/SNET64" and got error "nn_distance_so.so" not found.
 So I checked the folder "structural_losses" just to find there is no file named "nn_distance_so.so" indeed. 
Then I run "make" in terminal to execute makefile, and got error "nsync.h not found" .So I followed the instructions on a web page, downloading .h files in https://github.com/google/nsync/tree/master/public this website to usr/include. 
And the file nn_distance_so.so is created successfully.
However, when I run "python train_SNET.py --classifier_model_path log/baseline/PointNet1024/model.ckpt --num_out_points 64 --log_dir log/SNET64" again, I got the error  _ZTIN10tensorflow8OpKernelE as the title describes.
I don't know how to fix it.
Can anybody help?
(use python 2.7 and gcc 5.4.0)

robot@robot-OMEN-by-HP-Obelisk-Desktop-875-1xxx:~/learning_to_sample/classification$ python train_SNET.py --classifier_model_path log/PointNet1024/model.ckpt --num_out_points 64 --log_dir log/SNET64
/usr/local/lib/python2.7/dist-packages/requests/__init__.py:83: RequestsDependencyWarning: Old version of cryptography ([1, 2, 3]) may cause slowdown.
  warnings.warn(warning, RequestsDependencyWarning)
External Losses (Chamfer-EMD) were not loaded.
Traceback (most recent call last):
  File "train_SNET.py", line 37, in <module>
    SAMPLER_MODEL = importlib.import_module(FLAGS.sampler_model)  # import network module
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/robot/learning_to_sample/classification/models/snet_model.py", line 11, in <module>
    from structural_losses.tf_nndistance import nn_distance
  File "/home/robot/learning_to_sample/classification/structural_losses/tf_nndistance.py", line 7, in <module>
    nn_distance_module = tf.load_op_library(osp.join(base_dir, 'tf_nndistance_so.so'))
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/load_library.py", line 56, in load_op_library
    lib_handle = py_tf.TF_LoadLibrary(library_filename, status)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/errors_impl.py", line 473, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.NotFoundError: /home/robot/learning_to_sample/classification/structural_losses/tf_nndistance_so.so: undefined symbol: _ZTIN10tensorflow8OpKernelE

**Comment by orendv** [comment]
Please make sure you are using the correct TF version. 
The classification code has been tested with Python 2.7.12, TensorFlow 1.2.1, CUDA 8.0 and cuDNN 5.1.1 on Ubuntu 16.04.

**Comment by TheJasal** [comment]
I use tensorflow 1.4.0.
So how to run the code on tensorflow 1.4.0 then .......

**Comment by TheJasal** [comment]
problem solved.
Thanks to Pointnet++ project. I find the way to fix the problem in READE.md in Pointnet++.
If you are using TF 1.4.0 or above ,simply replace the g++ commands in makefile to  
the following sentence:
g++ -std=c++11 tf_xxxx.cpp tf_xxxx_g.cu.o -o tf_xxxx_so.so -shared -fPIC -I /usr/local/lib/python2.7/dist-packages/tensorflow/include -I /usr/local/cuda-8.0/include -I /usr/local/lib/python2.7/dist-packages/tensorflow/include/external/nsync/public -lcudart -L /usr/local/cuda-8.0/lib64/ -L/usr/local/lib/python2.7/dist-packages/tensorflow -ltensorflow_framework -O2 -D_GLIBCXX_USE_CXX11_ABI=0
where xxxx represents approxmatch or nndistance.
I close the issue,thanks.

**Comment by skq-5233** [comment]
> problem solved.
> Thanks to Pointnet++ project. I find the way to fix the problem in READE.md in Pointnet++.
> If you are using TF 1.4.0 or above ,simply replace the g++ commands in makefile to
> the following sentence:
> g++ -std=c++11 tf_xxxx.cpp tf_xxxx_g.cu.o -o tf_xxxx_so.so -shared -fPIC -I /usr/local/lib/python2.7/dist-packages/tensorflow/include -I /usr/local/cuda-8.0/include -I /usr/local/lib/python2.7/dist-packages/tensorflow/include/external/nsync/public -lcudart -L /usr/local/cuda-8.0/lib64/ -L/usr/local/lib/python2.7/dist-packages/tensorflow -ltensorflow_framework -O2 -D_GLIBCXX_USE_CXX11_ABI=0
> where xxxx represents approxmatch or nndistance.
> I close the issue,thanks.

Hello there! I followed your method and the result still shows the same error

**Comment by itailang** [comment]
Dear @skq-5233 ,
I updated the installation instructions for a more recent environment spec (TensorFlow 1.13.2, CUDA 10.0 and cuDNN 7.6.2). I highly recommend to use this environment spec instead of TensorFlow 1.4.0.

**Comment by skq-5233** [comment]
Thank you for your reply, I have solved it.


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Itai Lang"<notifications@github.com&gt;;
发送时间:&nbsp;2020年6月28日(星期天) 晚上7:32
收件人:&nbsp;"orendv/learning_to_sample"<learning_to_sample@noreply.github.com&gt;;
抄送:&nbsp;"Dandelion's Fled"<794919561@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [orendv/learning_to_sample] tensorflow.python.framework.errors_impl.NotFoundError: /home/robot/learning_to_sample/classification/structural_losses/tf_nndistance_so.so: undefined symbol: _ZTIN10tensorflow8OpKernelE (#3)





 
Dear @skq-5233 ,
 I updated the installation instructions for a more recent environment spec (TensorFlow 1.13.2, CUDA 10.0 and cuDNN 7.6.2). I highly recommend to use this environment spec instead of TensorFlow 1.4.0.

**Comment by itailang** [comment]
Great! Can you please share your solution?

**Comment by skq-5233** [comment]
Delete ABI =0 in the makefile&nbsp;



---Original---

**Comment by cpayal** [comment]
How to get around this error when using a conda environment?

**Comment by itailang** [comment]
@cpayal,
Please run the installation instructions from within the conda environment (after it is activated).

**Comment by wzm2256** [comment]
I also ran into a very similar problem :tensorflow.python.framework.errors_impl.NotFoundError: /home/wzm/CodeSet/SNET/classification/structural_losses/tf_approxmatch_so.so: undefined symbol: _ZN10tensorflow12OpDefBuilder5InputESs

I use tf=1.13 python=2.7 cuda=10.0 as suggested by @itailang , but the problem remains.


I solved it with @skq-5233 's method.
By the way,
that is not a 'ABI' variable.
It is actually 'D_GLIBCXX_USE_CXX11_ABI'.

Deleting this variable in two .sh files makes everything works well.

**Comment by itailang** [comment]
@wzm2256,
Thank you for sharing the solution!

**Comment by JudyCodes321** [comment]
delete " -D_GLIBCXX_USE_CXX11_ABI=0". There are two in my codes!
I only delete one and I meet this issue. Find out if there are other commands!

**Comment by itailang** [comment]
Dear @Iam-Jane,
Thank you for your comment. I fixed the compilation commands.

**Comment by lihanxing** [comment]
My solution to this problem is as follows. Hope it can help other people.
```
nvcc = /usr/local/cuda-10.0/bin/nvcc
cudalib = /usr/local/cuda-10.0/lib64/
tensorflow = /databank/home/lihanxing/anaconda3/envs/att/lib/python3.6/site-packages/tensorflow/include/

all: tf_approxmatch_so.so tf_approxmatch_g.cu.o tf_nndistance_so.so tf_nndistance_g.cu.o


tf_approxmatch_so.so: tf_approxmatch_g.cu.o tf_approxmatch.cpp
	g++ -std=c++11 tf_approxmatch.cpp tf_approxmatch_g.cu.o -o tf_approxmatch_so.so -shared -fPIC -I $(tensorflow) -lcudart -L $(cudalib) -O2 -D_GLIBCXX_USE_CXX11_ABI=0 -I $TF_INC -I /databank/home/lihanxing/anaconda3/envs/att/lib/python3.6/site-packages/tensorflow/include/external/nsync/public -L $TF_LIB -L /databank/home/lihanxing/anaconda3/envs/att/lib/python3.6/site-packages/tensorflow/ -ltensorflow_framework


tf_approxmatch_g.cu.o: tf_approxmatch_g.cu
	$(nvcc) -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++11 -c -o tf_approxmatch_g.cu.o tf_approxmatch_g.cu -I $(tensorflow) -DGOOGLE_CUDA=1 -x cu -Xcompiler -fPIC -O2 -I $TF_INC -I$TF_INC/external/nsync/public -L$TF_LIB -ltensorflow_framework


tf_nndistance_so.so: tf_nndistance_g.cu.o tf_nndistance.cpp
	g++ -std=c++11 tf_nndistance.cpp tf_nndistance_g.cu.o -o tf_nndistance_so.so -shared -fPIC -I $(tensorflow) -lcudart -L $(cudalib) -O2 -D_GLIBCXX_USE_CXX11_ABI=0 -I $TF_INC -I /databank/home/lihanxing/anaconda3/envs/att/lib/python3.6/site-packages/tensorflow/include/external/nsync/public -L $TF_LIB -L /databank/home/lihanxing/anaconda3/envs/att/lib/python3.6/site-packages/tensorflow/ -ltensorflow_framework


# /usr/local/cuda-10.0/bin/nvcc -std=c++11 -c -o tf_nndistance_g.cu.o tf_nndistance_g.cu -I $TF_INC -DGOOGLE_CUDA=1 -x cu -Xcompiler -fPIC -O2
# g++ -std=c++11 tf_nndistance.cpp tf_nndistance_g.cu.o -o tf_nndistance_so.so -shared -fPIC -I $TF_INC -I /usr/local/cuda-10.0/include -I $TF_INC/external/nsync/public -lcudart -L /usr/local/cuda-10.0/lib64/ -L$TF_LIB -ltensorflow_framework -O2 -D_GLIBCXX_USE_CXX11_ABI=0


tf_nndistance_g.cu.o: tf_nndistance_g.cu
	$(nvcc) -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++11 -c -o tf_nndistance_g.cu.o tf_nndistance_g.cu -I $(tensorflow) -DGOOGLE_CUDA=1 -x cu -Xcompiler -fPIC -O2 -I $TF_INC -I$TF_INC/external/nsync/public -L$TF_LIB -ltensorflow_framework

clean:
	rm tf_approxmatch_so.so
	rm tf_nndistance_so.so
	rm  *.cu.o 
```

**Comment by itailang** [comment]
@lihanxing,
Thanks for sharing your solution!
