### ISSUE TITLE
retrieval

### ISSUE THREAD

**Issue by ZhangYi0810** [orendv/learning_to_sample#6]
Unable to open file (unable to open file: name = 'log/AS_Net32/sampled/ply_data_test0.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)

**Comment by ZhangYi0810** [comment]
could you help me to solve the problem? Sir

**Comment by itailang** [comment]
Dear @Yerless,
It seems like there is a problem with the path to file. I suggest the following:
1. Check that the file exists.
2. Check that the path is correct (in terms of small and capital letters).
3. Use the full file path instead of the relative file path.

**Comment by Yerless** [comment]
Thank you! Sir, I have soled the problem.

**Comment by ZhangYi0810** [comment]
Thank you! Sir, I have solved the problem.
