### ISSUE TITLE
FPS or RS training for Classification

### ISSUE THREAD

**Issue by ZhangYi0810** [orendv/learning_to_sample#7]
Hey! Could you show me how to get classification accuracy through random sampling, Is it also 500 rounds of training?

**Comment by orendv** [comment]
Hi,
Thank you for taking interest in our project.
For random sampling, you don't need to train a sampling network.
To get a random sample of k points, just run a random permutation on the list of points, and then keep the first k points.

**Comment by ZhangYi0810** [comment]
Fine! Thanks for your help.
