### ISSUE TITLE
Performance issues in classification/evaluate_from_files.py(P2)

### ISSUE THREAD

**Issue by DLPerf** [orendv/learning_to_sample#8]
Hello,I found a performance issue in the definition of `evaluate` ,
classification/evaluate_from_files.py,
[sess = tf.Session(config=config)](https://github.com/orendv/learning_to_sample/blob/99e977e1c53ec0fa8b2b8a5151a56d0d088f6f78/classification/evaluate_from_files.py#L76)  was repeatedly called in [for pc_size in pc_sizes:](https://github.com/orendv/learning_to_sample/blob/99e977e1c53ec0fa8b2b8a5151a56d0d088f6f78/classification/evaluate_from_files.py#L155) and was not closed.
I think it will increase the efficiency and avoid out of memory if you close this session after using it.

Here are two files to support this issue,[support1](https://www.tensorflow.org/versions/r1.15/api_docs/python/tf/Session.html#close) and [support2](https://stackoverflow.com/questions/48051647/tensorflow-how-to-perform-image-categorisation-on-multiple-images)

Looking forward to your reply. Btw, I am very glad to create a PR to fix it if you are too busy.

**Comment by itailang** [comment]
Drear @DLPerf,

Thank you for flagging this. Can you please create a PR, as you suggested?

**Comment by itailang** [comment]
Closing the issue due to inactivity.
